version: "3.9"

# Definicion de servicios o contenedores que se desplegaran en la orquestacion
services:

  # Definicion de cada servicio o contenedor, es lo similar con lo que se realiza
  # en el docker run y demas comandos
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    #container_name: msvc-usuarios
    #image: usuarios:latest  # Se quito el iamge porque ahora se contruira la imagen
    # en el mismo archivo
    build:
      context: ./
      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always


  msvc-cursos:
    #container_name: msvc-cursos
    #image: cursos:latest
    build:
      context: ./
      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always

# Definicion de volumenes para las bases de datos con un name
# para que al momento de levantar no cambie el nombre
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring