version: "3.9"

# Definicion de servicios o contenedores que se desplegaran en la orquestacion
services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-cursos:
    container_name: msvc-cursos
    #image: cursos:latest
    # Crear imagen desde un dockerfile pero desde docker-compose
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    # va a buscar la version al repositorio de docker hub
    image: jesusvc/cursos
    ports:
      - "8002:8002"
    #env_file: ./msvc-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: root1234
      USUARIOS_URL: ec2-3-86-250-98.compute-1.amazonaws.com:8001
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring